# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MlemMlem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MlemMlem

  # Networking
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'

  # Google SDK
  pod 'GoogleSignIn'

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  
  # Supports
  pod 'IQKeyboardManagerSwift'
  pod 'KeychainAccess'
  pod 'SnapKit'
  pod 'R.swift'

end
